"""empty message

Revision ID: d894ff600917
Revises: 1b57f1ae9aec
Create Date: 2020-01-19 23:56:36.097193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd894ff600917'
down_revision = '1b57f1ae9aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'details', 'user', ['user_id'], ['id'])
    op.drop_column('details', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details', sa.Column('users_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'details', type_='foreignkey')
    # ### end Alembic commands ###
