"""empty message

Revision ID: ed2ec8896a52
Revises: f34bf19104d9
Create Date: 2020-01-19 17:44:50.047526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed2ec8896a52'
down_revision = 'f34bf19104d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_creation_date', table_name='location')
    op.drop_index('lat', table_name='location')
    op.drop_index('long', table_name='location')
    op.drop_index('name', table_name='location')
    op.drop_table('location')
    op.drop_table('device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('d_type', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('location',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('long', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('lat', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('creation_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='location_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'location', ['name'], unique=True)
    op.create_index('long', 'location', ['long'], unique=True)
    op.create_index('lat', 'location', ['lat'], unique=True)
    op.create_index('ix_location_creation_date', 'location', ['creation_date'], unique=False)
    # ### end Alembic commands ###
